import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Questrial } from "next/font/google";

import "./globals.css";
import "animate.css";
import { ActionsProvider } from "@/context/ActionsContext";
import { Header } from "@/components/Header";
// import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Maheus Rodrigues",
  description: "Generated by create next app",
};

const questrial = Questrial({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-questrial",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={questrial.variable} suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="font-questrial">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ActionsProvider>
            <Header />
            {children}
            {/* <Footer /> */}
          </ActionsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
